name: Test and Generate Allure Report

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm install

      - name: Run Mocha tests
        run: npm test
      
      - name: Generate Allure Report
        uses: allure-framework/allure-github-action@v1
        with:
          allure-command: generate
          results-folder: ./test-results
          report-folder: ./allure-report
          delete-previous-results: true

  test2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm install

      - name: Run Mocha tests 2
        run: npm run test2
      
      - name: Generate Allure Report 2
        uses: allure-framework/allure-github-action@v1
        with:
          allure-command: generate
          results-folder: ./test-results2
          report-folder: ./allure
